-- Create the contact_submissions table
CREATE TABLE contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service TEXT NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  company TEXT,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public (anonymous) insertions
-- This is necessary since the form submits directly from the client using the anon key
CREATE POLICY "Allow public insertions" ON contact_submissions
FOR INSERT WITH CHECK (true);

-- Optional: Create a policy to allow only authenticated users to view submissions
CREATE POLICY "Allow authenticated users to view" ON contact_submissions
FOR SELECT TO authenticated USING (true);
